project_name: direct-csi-driver

release:
   name_template: "Version {{.Version}}"

   github:
    owner: minio
    name: direct-csi-driver

before:
  hooks:
    - go mod tidy

builds:
  -
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags="osusergo netgo static_build"
    ldflags:
      - -s -w -X github.com/minio/direct-csi-driver/cmd.Version={{ .Version }}

archives:
  - format: binary

changelog:
  sort: asc

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - minio/direct-csi-driver:{{ .Tag }}
      - minio/direct-csi-driver:latest
