project_name: direct-csi

release:
   name_template: "Release version {{.Version}}"

   github:
    owner: minio
    name: direct-csi

   extra_files:
     - glob: "*.minisig"
     - glob: "*.zip"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  -
    main: ./cmd/direct-csi
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags="osusergo netgo static_build"
    ldflags:
      - -s -w -X main.Version={{ .Tag }}

  -
    main: ./cmd/kubectl-direct_csi
    id: kubectl-direct_csi
    binary: kubectl-direct_csi
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags="osusergo netgo static_build"
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
    hooks:
      post: ./package.sh {{ .Path }}

archives:
  -
    allow_different_binary_count: true
    format: binary

changelog:
  sort: asc

dockers:
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-amd64-rhel7"
  use_buildx: true
  goarch: amd64
  dockerfile: Dockerfile.rhel7
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-ppc64le-rhel7"
  use_buildx: true
  goarch: ppc64le
  dockerfile: Dockerfile.rhel7
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-s390x-rhel7"
  use_buildx: true
  goarch: s390x
  dockerfile: Dockerfile.rhel7
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-arm64-rhel7"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile.rhel7
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-amd64"
  use_buildx: true
  goarch: amd64
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-ppc64le"
  use_buildx: true
  goarch: ppc64le
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/ppc64le"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-s390x"
  use_buildx: true
  goarch: s390x
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/s390x"
- image_templates:
  - "quay.io/minio/direct-csi:{{ .Tag }}-arm64"
  use_buildx: true
  goarch: arm64
  dockerfile: Dockerfile
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - "--platform=linux/arm64"
docker_manifests:
- name_template: quay.io/minio/direct-csi:{{ .Tag }}
  image_templates:
  - quay.io/minio/direct-csi:{{ .Tag }}-amd64
  - quay.io/minio/direct-csi:{{ .Tag }}-arm64
  - quay.io/minio/direct-csi:{{ .Tag }}-ppc64le
  - quay.io/minio/direct-csi:{{ .Tag }}-s390x
- name_template: quay.io/minio/direct-csi:latest
  image_templates:
  - quay.io/minio/direct-csi:{{ .Tag }}-amd64
  - quay.io/minio/direct-csi:{{ .Tag }}-arm64
  - quay.io/minio/direct-csi:{{ .Tag }}-ppc64le
  - quay.io/minio/direct-csi:{{ .Tag }}-s390x
- name_template: quay.io/minio/direct-csi:{{ .Tag }}-rhel7
  image_templates:
  - quay.io/minio/direct-csi:{{ .Tag }}-amd64-rhel7
  - quay.io/minio/direct-csi:{{ .Tag }}-arm64-rhel7
  - quay.io/minio/direct-csi:{{ .Tag }}-ppc64le-rhel7
  - quay.io/minio/direct-csi:{{ .Tag }}-s390x-rhel7
